name: Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: eks_runner
    container: amazonlinux:2  # Ensures AWS CLI is available
    steps:
      - name: Install AWS CLI
        run: |
          yum install -y aws-cli
          aws sts get-caller-identity

      - name: List ECR Repositories
        run: |
          aws ecr describe-repositories --region us-east-1
