name: Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: eks_runner
    container: amazon/aws-cli:latest  # Ensures AWS CLI is available
    steps:
      - name: Print identity
        run: |
          aws sts get-caller-identity

      - name: List ECR Repositories
        run: |
          aws ecr describe-repositories --region us-east-1
